[toolchain]
solana_version = "1.17.34"

[features]
seeds = false
skip-lint = false

[programs.localnet]
bid_wall = "WALL8ucBuUyL46QYxwYJjidaFYhdvxUFrgvBxPshERx"
conditional_vault = "VLTX1ishMBbcX3rdBWGssxawAo1Q2X2qxYFYqiGodVg"
futarchy = "FUTARELBfJfQ8RDGhg1wdhddq1odMAJUePHFuBYfUxKq"
gated_mint = "GaTEjZy6eMdHg2BcL8dk3iE78jkJ9sPtyw1q2tMNi8PA"
launchpad = "MooNyh4CBUYEKyXVnjGYQ8mEiJDpGvJMdvrZx1iGeHV"
launchpad_v7 = "moontUzsdepotRGe5xsfip7vLPTJnVuafqdUWexVnPM"
launchpad_v8 = "moonDJUoHteKkGATejA5bdJVwJ6V6Dg74gyqyJTx73n"
liquidation = "LiQnowFbFQdYyZhF4pUbpsrZCjxRTQ1upKJxZ2VXjde"
mint_governor = "gvnr27cVeyW3AVf3acL7VCJ5WjGAphytnsgcK1feHyH"
performance_package_v2 = "pPV2pfrxnmstSb9j7kEeCLny5BGj6SNwCWGd6xbGGzz"
price_based_performance_package = "pbPPQH7jyKoSLu8QYs3rSY3YkDRXEBojKbTgnUg7NDS"
relaunch = "vaMpdXN2P3Z5v8y6GtAU5NzCUjxtphnRVpvqu37Spik"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
assign-permissionless-account = "yarn run tsx scripts/assignPermissionlessAccount.ts"
claim-all-launch = "yarn run tsx scripts/v0.5/claimAllLaunch.ts"
execute-proposal = "yarn run tsx scripts/v0.5/squads/executeProposal.ts"
finalize-launch = "yarn run tsx scripts/v0.5/finalizeLaunch.ts"
initialize-dao = "yarn run tsx scripts/v0.6/initializeDao.ts"
initialize-launch = "yarn run tsx scripts/initializeLaunch.ts"
initialize-proposal = "yarn run tsx scripts/v0.5/initializeProposal.ts"
migrate-meta = "yarn run tsx scripts/v0.5/migrateMeta.ts"
remove-spending-limit = "yarn run tsx scripts/v0.5/squads/removeSpendingLimit.ts"
start-launch = "yarn run tsx scripts/v0.5/startLaunch.ts"
test = "npx mocha --import=tsx --bail tests/main.test.ts --timeout 5000"
transfer = "yarn run tsx scripts/v0.5/squads/initializeTransferProposal.ts"
update-spending-limit = "yarn run tsx scripts/v0.5/squads/updateSpendingLimit.ts"
use-spending-limit = "yarn run tsx scripts/v0.5/squads/useSpendingLimit.ts"
v03-add-metadata = "yarn run tsx scripts/v0.3/uploadMetadata.ts"
v04-add-metadata = "yarn run tsx scripts/v0.4/uploadMetadata.ts"
v04-initialize-dao = "yarn run tsx scripts/v0.4/initializeDao.ts"
v04-initialize-proposal = "yarn run tsx scripts/v0.4/initializeProposal.ts"
v05-execute-proposal = "yarn run tsx scripts/v0.5/executeProposal.ts"
v06-launch = "yarn run tsx scripts/v0.6/launch.ts"
claim-launch = "yarn run tsx scripts/v0.6/claimAllLaunch.ts"
v06-execute-proposal = "yarn run tsx scripts/v0.6/executeProposal.ts"
v06-execute-general-proposal = "yarn run tsx scripts/v0.6/executeGeneralProposal.ts"
v06-dump-daos-proposals = "yarn run tsx scripts/v0.6/dumpDaosProposals.ts"
v06-migrate-daos-proposals = "yarn run tsx scripts/v0.6/migrateDaosProposals.ts"
v06-create-dao = "yarn run tsx scripts/v0.6/createDao.ts"
v06-provide-liquidity = "yarn run tsx scripts/v0.6/provideLiquidity.ts"
v06-collect-meteora-damm-fees = "yarn run tsx scripts/v0.6/collectMeteoraDammFees.ts"
v06-return-funds = "yarn run tsx scripts/v0.6/returnFunds.ts"
v06-dump-daos = "yarn run tsx scripts/v0.6/dumpDaos.ts"
v06-migrate-daos = "yarn run tsx scripts/v0.6/migrateDaos.ts"
v06-sponsor-proposal = "yarn run tsx scripts/v0.6/sponsorProposal.ts"
v07-collect-meteora-damm-fees = "yarn run tsx scripts/v0.7/collectMeteoraDammFees.ts"
v07-launch-template = "yarn run tsx scripts/v0.7/launchTemplate.ts"
v07-start-launch = "yarn run tsx scripts/v0.7/startLaunch.ts"
v07-complete-launch = "yarn run tsx scripts/v0.7/completeLaunch.ts"
v07-claim-all-launch = "yarn run tsx scripts/v0.7/claimAllLaunch.ts"
v07-approve-points-based = "yarn run tsx scripts/v0.7/pointsBased/approveWithPointsWeightedPhase.ts"
v07-close-launch = "yarn run tsx scripts/v0.7/closeLaunch.ts"
v07-initialize-performance-package = "yarn run tsx scripts/v0.7/initializePerformancePackage.ts"
v07-claim-launch-additional-tokens = "yarn run tsx scripts/v0.7/claimLaunchAdditionalTokens.ts"
v07-remove-proposal = "yarn run tsx scripts/v0.7/removeProposal.ts"
v07-audit-liquidity-position-authorities = "yarn run tsx scripts/v0.7/auditLiquidityPositionAuthorities.ts"
v07-fix-position-authorities = "yarn run tsx scripts/v0.7/fixPositionAuthorities.ts"
v07-dump-launches-funding-records = "yarn run tsx scripts/v0.7/dumpLaunchesAndFundingRecords.ts"
v07-resize-launches-funding-records = "yarn run tsx scripts/v0.7/resizeLaunchesAndFundingRecords.ts"
v07-dump-launches = "yarn run tsx scripts/v0.7/dumpLaunches.ts"
v07-resize-launches = "yarn run tsx scripts/v0.7/resizeLaunches.ts"
v07-dump-daos = "yarn run tsx scripts/v0.7/dumpDaos.ts"
v07-resize-daos = "yarn run tsx scripts/v0.7/resizeDaos.ts"
v07-extend-launch = "yarn run tsx scripts/v0.7/extendLaunch.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "opnb2LAfJYbRMAHHvqjCwQxanZn7ReEHp1k81EohpZb"
program = "./tests/fixtures/openbook_v2.so"

[[test.genesis]]
address = "TWAP7frdvD3ia7TWc8e9SxZMmrpd2Yf3ifSPAHS8VG3"
program = "./tests/fixtures/openbook_twap.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/fixtures/mpl_token_metadata.so"

[[test.genesis]]
address = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
program = "./tests/fixtures/pump_amm.so"

[[test.genesis]]
address = "pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ"
program = "./tests/fixtures/pump_fees.so"

[[test.genesis]]
address = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"
program = "./tests/fixtures/whirlpool.so"

[[test.genesis]]
address = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
program = "./tests/fixtures/raydium_amm.so"
